config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :jobs
  resources :companies
  resources :comments
  resources :job_comments, only:[:create]
  resources :favorite_jobs, only: [:create, :index]

  get '/login'                => redirect('/auth/github'), as: :login
  get '/signout'              => 'sessions#destroy',       as: :signout
  get '/auth/github/callback' => 'sessions#create'
  get '/auth/failure'         => 'sessions#failure'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company
  has_many   :users, through: :favorite_jobs
  has_many   :favorite_jobs


  def job_builder(json_response)
    json_response.each do |job|

      company = Company.find_or_create_by(name: job["company"])
      company_id = company.id
      new_job = company.jobs.new

      new_job.title              = job["title"]
      new_job.description        = job["description"]
      new_job.github_id          = job["github_id"]
      new_job.github_created_at  = job["github_created_at"]
      new_job.location           = job["location"]
      new_job.job_type           = job["type"]
      new_job.how_to_apply       = job["how_to_apply"]
      new_job.github_url         = job["github_url"]
      new_job.company_name       = job["company"]
      new_job.company_logo       = job["company_logo"]
      new_job.company_id         = company_id

      new_job.save
    end
  end

  def self.remote_entries
    JobFetcher::Remote.new.entries
  end

  def self.entries
    JobFetcher::StackExchange.new.entries
  end

  def self.build_remote_jobs(remote_entries)
    remote_entries.each do |entry|
      self.create(title: entry.title,
      description: entry.description,
      url: entry.source_url,
      posted_on: entry.posted_on,
      user_created: false,
      remote: true
      )
    end
  end


  def self.build_jobs(entries)
    entries.each do |entry|
      self.create(title: entry.title,
                  description: entry.description,
                  url: entry.source_url,
                  posted_on: entry.posted_on,
                  user_created: false,
                  location: entry.title.split(' ')[-4..-1].join[/\(.+/].delete(")("),
                  remote: false

                 )
    end
  end


  def self.unique_locations
    Job.all.map { |job| job.location }.uniq.reject{ |j| j == nil }
  end

  def self.clear_jobs
    self.where(user_created: false).delete_all
  end

  def self.build_all_jobs(remote_entries, entries)
    build_remote_jobs(remote_entries)
    build_jobs(entries)
  end
  


end

app/controllers/jobs_controller.rb
class JobsController < AuthorizationController

  def index
    @jobs    = Job.all
    @locations = Job.unique_locations
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find(params[:id])
    @comment = Comment.new
  end

  def create
    @job = Job.create!(job_params)
    redirect_to jobs_path
  end

  def create_from_github
    # This is dead code
    description = params["job"]["description"]
    location    = params["job"]["location"]
    options   = "description=#{description}&location=#{location}"
    response  = Faraday.get("https://jobs.github.com/positions.json?#{options}&client_id=#{ENV['GITHUB_KEY']}&client_secret=#{ENV['GITHUB_SECRET']}")
    job       = Job.new
    get_json  = JSON.parse(response.body)
    job.job_builder(get_json)
  end

  private

  def job_params
    params.require(:job).permit(:title,
                                :description,
                                :company_id,
                                :github_id,
                                :github_created_at,
                                :location,
                                :job_type,
                                :how_to_apply,
                                :company_name,
                                :company_url,
                                :company_logo,
                                :github_url,
                                :full_time)
  end


end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_filters.html.erb
<div id="filter-wrapper" class="collapse in">
  <h3>Filters</h3>
  <div class= 'location filter-buttons' data-toggle="buttons">
    <h5>Location</h5>
    <% @locations.each do |location| %>
      <label id="<%= location.to_s.delete("' ',/;")%>" class="btn btn-primary btn-xs filter-button">
        <input type="radio" autocomplete="off" value=<%= location %>> <%= location %>
      </label>
    <% end %>
    <h5>Job Type</h5>
    <label id= 'true' class='btn btn-primary btn-xs filter-button'>
      <input type="radio" autocomplete="off">Remote
    </label>
    <label id= 'false' class='btn btn-primary btn-xs filter-button'>
      <input type="radio" autocomplete="off">On-Site
    </label>
  </div>
</div>

app/views/jobs/_github.html.erb
<br><br><br>
<h1 style="margin-bottom: 30px;"> Add Jobs from Github </h1>

<div style="width: 50%; padding-bottom: 100px;">
  <%= form_for @job, url: jobs_path do |f| %>
    <%= f.text_field :description, id: "github_description", placeholder: "Description", class:"input_class"%>
    <br><br>
    <%= f.text_field :location, id: "github_location", placeholder: "Location", class:"input_class"  %>
    <br><br>
    <%= f.text_field :job_type, placeholder: "Job Type", class:"input_class"  %>
    <br><br>
    <%= f.submit "Retrieve jobs from Github" %>
  <% end %>
</div>

app/views/jobs/_job.html.erb
<div class="jobs_rp" id="job_<%= job.id %>">
  <div class="<%=job.location.to_s.delete("' ',/;")%> <%= job.remote %>  hide-locations">
    <%= link_to job do %>
      <h2 class="job_title_index"><%= job.title %></h2>
    <% end %>

    <% if job.company %>
      <h5>
        <%= link_to job.company.name, company_path(job.company.id), class: "job_company_index" %>
      </h5>
    <% end %>

    <div class='panel-body'>
      <%= link_to "#{job.url}", job.url %>
      <div><%= "via #{job.posted_on}" if job.posted_on %></div>
      <div><%= sanitize job.description.truncate(250) %></div>
      <div class="favorite-btn">
        <%= button_to 'Favorite this job!', favorite_jobs_path(job_id: job.id), method: "post",
        remote: true,
        class: 'btn btn-default btn-xs favorite' %>
      </div>
    </div>

  </div>
</div>

app/views/jobs/index.html.erb
<%= render :partial => 'job', :collection => @jobs %>

app/views/jobs/new.html.erb
<%= link_to "Back to Jobs", jobs_path, class:"btn btn-default btn-sm filter-btn" %>

<div style="width: 70%">
  <h1 style="margin-bottom: 30px;"> Add a Job manually </h1>
  <%= form_for @job do |f| %>
    <%= f.text_field :title, placeholder: "Title", class:"input_class" %>
    <br><br>
    <%= f.text_area :description, placeholder: "Description", class:"input_class", rows:8 %>
    <br><br>
    <%= f.text_field :location, placeholder: "Location", class:"input_class" %>
    <br><br>
    <%= f.text_area :how_to_apply, placeholder: "How to apply", class:"input_class", rows:3  %>
    <br><br>
    <%= f.text_field :company_name, placeholder: "Company Name", class:"input_class" %>
    <br><br>
    <%= f.text_field :company_url, placeholder: "Website", class:"input_class" %>
    <br><br>
    <%= f.text_field :remote, class:"input_class" %>
    <br><br>
    <%= f.submit "Save", :id => 'save_job' %>
  <% end %>
</div>

app/views/jobs/show.html.erb
<%= link_to "Back to Jobs", jobs_path, class:"btn btn-default btn-sm filter-btn" %>

<div id='job-wrapper'>

  <div class='job_page'>
    <h1 style="color:#22c2d0; margin-bottom: -5px"><%= @job.title %></h1>
    <% if @job.company %>
      <%= link_to @job.company.name, company_path(@job.company) %><br>
    <% end %>
    <br>
    <%= @job.url %>
    <div><%= @job.posted_on ? "This job was posted originaly on #{@job.posted_on}" : "" %></div>

    <div><%= sanitize @job.description %></div>
  </div>

</div>