config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :jobs
  resources :companies
  resources :comments
  resources :job_comments, only:[:create]
  resources :favorite_jobs, only: [:create, :index]

  get '/login'                => redirect('/auth/github'), as: :login
  get '/signout'              => 'sessions#destroy',       as: :signout
  get '/auth/github/callback' => 'sessions#create'
  get '/auth/failure'         => 'sessions#failure'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :comments
  has_many :jobs
  has_many :company_connections
  has_many :connections, through: :company_connections
end

app/controllers/companies_controller.rb
class CompaniesController < AuthorizationController
  def index
    @companies = Company.all
  end

  def show
    @company  = Company.find(params[:id])
    @comments = @company.comments
    @comment  = Comment.new
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

app/views/companies/edit.html.erb
<h1>Companies#edit</h1>
<p>Find me in app/views/companies/edit.html.erb</p>

app/views/companies/index.html.erb
<div class="container">
  <%= @companies.each do |c| %>
   <h3> Company Name: <strong><%= c.name %></strong> </h3>
   <h4> Company Description: <strong><%= c.description %></strong> </h4>
 <% end %>
</div>

app/views/companies/new.html.erb
<h1>Companies#new</h1>
<p>Find me in app/views/companies/new.html.erb</p>

app/views/companies/show.html.erb
<%= link_to "Back to Jobs", jobs_path, class:"btn btn-default btn-sm filter-btn" %>

<h1 class="job_title_index"><%= @company.name %></h1>
<h4><%= @company.description %></h4>
<h4><%= @company.team_size %></h4>


<div class="comment_section">
  <div class="news_wrapper">
    <h3 class="text-center"> Company News </h3>
    <br>
    <%= form_for(@comment, url: comments_path(id: @company.id), html: { method: :post }) do |f| %>
      <%= f.text_field :title, placeholder: "What's happening?", class:"input_class" %>
      <br>
      <br/>
      <%= f.text_area :content, placeholder:"Details, please!", class:"input_class", rows:3%>
      <br><br>
      <%= f.hidden_field :author, value: current_user.name %>
      <%= f.submit "Publish" %>
    <% end  %>

    <br><br>

    <div>
      <% @comments.each do |comment| %>
      <div class="author_news"><%= comment.author %> said:</div>
      <div class="title_news"><%= comment.title %></div>
        <div class="comment_news"><%= comment.content %></div>
      <!-- <%= link_to "Edit", edit_comment_path(comment_id: comment.id) %> -->
<br><br>
      <% end %>
    </div>
  </div>
</div>



  <h4 style="margin-bottom: 70px;"> <%=@company.jobs.count %>  available Jobs!</h4>
<div style="width:70%">

  <% @company.jobs.map  do |job| %>
  <%= link_to  job_path(job) do %>
    <div class="<%=job.location.to_s.delete("' ',/;")%> <%= job.remote %>  hide-locations">
      <h4 class=" <%=job.id%> job_title_index"><%= job.title %></h4>

      <% end %>

      <div class='panel-body'>
        <%= link_to "#{job.url}", job.url %>
        <div><%= job.posted_on ? "This job was posted originaly on #{job.posted_on}" : "" %></div>
        <div><%= sanitize job.description.truncate(250)  %></div>
        <div class="favorite-btn">
          <%= button_to favorite_jobs_path(job_id: job.id), method: "post",
          remote: true,
          class: 'btn btn-default btn-xs favorite' do%>
          <i class="fa fa-star"> </i> Favorite this job!
          <% end %>
          <hr>
        </div>
      </div>

  </div>
  <% end %>

</div>

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>